### ISSUE TITLE
[dcat:theme and dct:type] Value must be an instance of skos:Concept

### ISSUE THREAD

**Issue by javicond3** [ISAITB/validator-resources-dcat-ap#2]
I used the [https://www.itb.ec.europa.eu/shacl/dcat-ap/upload](https://www.itb.ec.europa.eu/shacl/dcat-ap/upload) to validate the following rdf against **DCAT-AP 2.0.1 Ranges Zero** and **DCAT-AP 2.0.1 Ranges**

```xml
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
  xmlns:foaf="http://xmlns.com/foaf/0.1/"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:dcat="http://www.w3.org/ns/dcat#"
  xmlns:dct="http://purl.org/dc/terms/"
  xmlns:skos="http://www.w3.org/2004/02/skos/core#"
>
  <dcat:Dataset>
    <dcat:theme rdf:resource="http://publications.europa.eu/resource/authority/data-theme/EDUC"/>
    <dcat:distribution>
      <dcat:Distribution>
        <dct:license>
        	<dct:LicenseDocument>
    			<dct:type rdf:resource="http://purl.org/adms/licencetype/PublicDomain"/>
  			</dct:LicenseDocument>
        </dct:license>
      </dcat:Distribution>
    </dcat:distribution>
    <dct:publisher>
      <foaf:Agent>
        <dct:type rdf:resource="http://purl.org/adms/publishertype/Academia-ScientificOrganisation"/>
        <foaf:name>exampleorg</foaf:name>
      </foaf:Agent>
    </dct:publisher>
  </dcat:Dataset>
</rdf:RDF>

```

I got the following errors:

- Value must be an instance of skos:Concept
	- Test: [Value] - [http://publications.europa.eu/resource/authority/data-theme/EDUC]
	- Location: [Result path] - [http://www.w3.org/ns/dcat#theme]
- Value must be an instance of skos:Concept
	- Test: [Value] - [http://purl.org/adms/licencetype/PublicDomain]
	- Location: [Result path] - [http://purl.org/dc/terms/type]
- Value must be an instance of skos:Concept
	- Test: [Value] - [http://purl.org/adms/publishertype/Academia-ScientificOrganisation]
	- Location: [Result path] - [http://purl.org/dc/terms/type]

However, in the three cases the values are tagged as `skos:Concept` in their original definition `<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>`. Links:

- [http://publications.europa.eu/resource/authority/data-theme/EDUC](http://publications.europa.eu/resource/authority/data-theme/EDUC)
- [http://purl.org/adms/licencetype/PublicDomain](http://purl.org/adms/licencetype/PublicDomain)
- [http://purl.org/adms/publishertype/Academia-ScientificOrganisation](http://purl.org/adms/publishertype/Academia-ScientificOrganisation)

**Comment by javicond3** [comment]
It could be solved by wrapping the elements inside `<skos:Concept>` **but it should not be required** as in the original source they are already defined as `skos:Concept`

Example of wrapping to solve **but not desirable**:

```xml
    <dcat:theme>
    	<skos:Concept rdf:about="http://publications.europa.eu/resource/authority/data-theme/EDUC"/>
    </dcat:theme>

```

**Comment by bertvannuffelen** [comment]
@javicond3 the inclusion of the controlled vocabularies is only done in the option: DCAT-AP 2.0.1 Controlled Vocabularies. (See https://github.com/ISAITB/validator-resources-dcat-ap/blob/master/resources/config.properties#L27) 

The reason for this split is two-fold:
   - reusers might have chosen another codelists for some properties and then the possible reuse of the shape file is easier
   - the loading of the codelists can take a while and thus giving users of the other range validation shapes the impression there is something wrong.

As the ranges check for the type, this codelist constrainted properties will probably fail without including the controlled vocabularies as the categorization of being a skos:Concept is part of the codelist. For coherency reasons I included them in the ranges* shape files.

Note that this split in several files is system/application agnostic. The split is based on the constraint type. Unfortunately there is no perfect split possible satisfying all possible usecases.

**Comment by javicond3** [comment]
Thanks a lot for the reply, it has all the sense that it is difficult to satisfy all the cases. 

However, I have tried to include the controlled vocabularies with the DCAT-AP 2.0.1 Ranges through the DCAT-AP Development option and the problem still remains. The problem is due to that the controlled vocabularies import (https://github.com/ISAITB/validator-resources-dcat-ap/blob/master/resources/config.properties#L29) only imports the http://publications.europa.eu/resource/authority/data-theme definition and not the http://publications.europa.eu/resource/authority/data-theme/EDUC (which is the one that types EDUC as a skos:Concept).

In order to include the controlled vocabularies with the other options I would propose the following alternatives:

- Include all the imports (e.g., http://publications.europa.eu/resource/authority/data-theme/EDUC): **this alternative is not scalable, so it is not recommended.**
- Use a logical "OR" to validate if its compilant to one of the controlled vocabularies "OR" ranges definition: this alternative should be implemented as a new option. **It allows to merge both options and it is scalable, so it would be the recommended one.**
