### ISSUE TITLE
API does not work with DCAT-AP v2.0.1

### ISSUE THREAD

**Issue by javicond3** [ISAITB/validator-resources-dcat-ap#3]
The API does not work with any option of version 2.0.1, it always answers "success" even if the RDF provided has errors or warnings.
It only happens with version 2.0.1: DCAT-AP 2.0.1 Base Zero, DCAT-AP 2.0.1 Ranges Zero,  DCAT-AP 2.0.1 Ranges Zero, DCAT-AP 2.0.1 Ranges Zero, etc.

**Comment by bertvannuffelen** [comment]
Hi @javicond3,

thanks for notifying this. Something is going wrong while reading the config, because when checking the used shapes (you can export them) they are empty.

kr,
Bert

**Comment by bertvannuffelen** [comment]
@javicond3 it should be fixed now.

**Comment by javicond3** [comment]
Thanks @bertvannuffelen, now it works well
